// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: websocket.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Websocket_WebSocketSend_FullMethodName  = "/websocket/webSocketSend"
	Websocket_IsOnlineUsers_FullMethodName  = "/websocket/isOnlineUsers"
	Websocket_GetOnlineCount_FullMethodName = "/websocket/getOnlineCount"
)

// WebsocketClient is the client API for Websocket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebsocketClient interface {
	// 发送websocket消息
	WebSocketSend(ctx context.Context, in *WebSocketSendReq, opts ...grpc.CallOption) (*WebSocketSendResp, error)
	// 获取用户是否在线
	IsOnlineUsers(ctx context.Context, in *IsOnlineUsersReq, opts ...grpc.CallOption) (*IsOnlineUsersResp, error)
	// 获取在线用户数
	GetOnlineCount(ctx context.Context, in *GetOnlineCountReq, opts ...grpc.CallOption) (*GetOnlineCountResp, error)
}

type websocketClient struct {
	cc grpc.ClientConnInterface
}

func NewWebsocketClient(cc grpc.ClientConnInterface) WebsocketClient {
	return &websocketClient{cc}
}

func (c *websocketClient) WebSocketSend(ctx context.Context, in *WebSocketSendReq, opts ...grpc.CallOption) (*WebSocketSendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebSocketSendResp)
	err := c.cc.Invoke(ctx, Websocket_WebSocketSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websocketClient) IsOnlineUsers(ctx context.Context, in *IsOnlineUsersReq, opts ...grpc.CallOption) (*IsOnlineUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsOnlineUsersResp)
	err := c.cc.Invoke(ctx, Websocket_IsOnlineUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websocketClient) GetOnlineCount(ctx context.Context, in *GetOnlineCountReq, opts ...grpc.CallOption) (*GetOnlineCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineCountResp)
	err := c.cc.Invoke(ctx, Websocket_GetOnlineCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsocketServer is the server API for Websocket service.
// All implementations must embed UnimplementedWebsocketServer
// for forward compatibility.
type WebsocketServer interface {
	// 发送websocket消息
	WebSocketSend(context.Context, *WebSocketSendReq) (*WebSocketSendResp, error)
	// 获取用户是否在线
	IsOnlineUsers(context.Context, *IsOnlineUsersReq) (*IsOnlineUsersResp, error)
	// 获取在线用户数
	GetOnlineCount(context.Context, *GetOnlineCountReq) (*GetOnlineCountResp, error)
	mustEmbedUnimplementedWebsocketServer()
}

// UnimplementedWebsocketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebsocketServer struct{}

func (UnimplementedWebsocketServer) WebSocketSend(context.Context, *WebSocketSendReq) (*WebSocketSendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WebSocketSend not implemented")
}
func (UnimplementedWebsocketServer) IsOnlineUsers(context.Context, *IsOnlineUsersReq) (*IsOnlineUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsOnlineUsers not implemented")
}
func (UnimplementedWebsocketServer) GetOnlineCount(context.Context, *GetOnlineCountReq) (*GetOnlineCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlineCount not implemented")
}
func (UnimplementedWebsocketServer) mustEmbedUnimplementedWebsocketServer() {}
func (UnimplementedWebsocketServer) testEmbeddedByValue()                   {}

// UnsafeWebsocketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebsocketServer will
// result in compilation errors.
type UnsafeWebsocketServer interface {
	mustEmbedUnimplementedWebsocketServer()
}

func RegisterWebsocketServer(s grpc.ServiceRegistrar, srv WebsocketServer) {
	// If the following call panics, it indicates UnimplementedWebsocketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Websocket_ServiceDesc, srv)
}

func _Websocket_WebSocketSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebSocketSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).WebSocketSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Websocket_WebSocketSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).WebSocketSend(ctx, req.(*WebSocketSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websocket_IsOnlineUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnlineUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).IsOnlineUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Websocket_IsOnlineUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).IsOnlineUsers(ctx, req.(*IsOnlineUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websocket_GetOnlineCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).GetOnlineCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Websocket_GetOnlineCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).GetOnlineCount(ctx, req.(*GetOnlineCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Websocket_ServiceDesc is the grpc.ServiceDesc for Websocket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Websocket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "websocket",
	HandlerType: (*WebsocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "webSocketSend",
			Handler:    _Websocket_WebSocketSend_Handler,
		},
		{
			MethodName: "isOnlineUsers",
			Handler:    _Websocket_IsOnlineUsers_Handler,
		},
		{
			MethodName: "getOnlineCount",
			Handler:    _Websocket_GetOnlineCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websocket.proto",
}
