// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: websocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketSendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`              // web, app, customer, admin
	ToUsers       []string               `protobuf:"bytes,2,rep,name=to_users,json=toUsers,proto3" json:"to_users,omitempty"` // 接收者 userid列表
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketSendReq) Reset() {
	*x = WebSocketSendReq{}
	mi := &file_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketSendReq) ProtoMessage() {}

func (x *WebSocketSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketSendReq.ProtoReflect.Descriptor instead.
func (*WebSocketSendReq) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketSendReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WebSocketSendReq) GetToUsers() []string {
	if x != nil {
		return x.ToUsers
	}
	return nil
}

func (x *WebSocketSendReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WebSocketSendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketSendResp) Reset() {
	*x = WebSocketSendResp{}
	mi := &file_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketSendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketSendResp) ProtoMessage() {}

func (x *WebSocketSendResp) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketSendResp.ProtoReflect.Descriptor instead.
func (*WebSocketSendResp) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{1}
}

type IsOnlineUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // web, app, customer, admin
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineUsersReq) Reset() {
	*x = IsOnlineUsersReq{}
	mi := &file_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineUsersReq) ProtoMessage() {}

func (x *IsOnlineUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineUsersReq.ProtoReflect.Descriptor instead.
func (*IsOnlineUsersReq) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *IsOnlineUsersReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *IsOnlineUsersReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type IsOnlineUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineUsersResp) Reset() {
	*x = IsOnlineUsersResp{}
	mi := &file_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineUsersResp) ProtoMessage() {}

func (x *IsOnlineUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineUsersResp.ProtoReflect.Descriptor instead.
func (*IsOnlineUsersResp) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *IsOnlineUsersResp) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetOnlineCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // web, app, admin,customer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineCountReq) Reset() {
	*x = GetOnlineCountReq{}
	mi := &file_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineCountReq) ProtoMessage() {}

func (x *GetOnlineCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineCountReq.ProtoReflect.Descriptor instead.
func (*GetOnlineCountReq) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnlineCountReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetOnlineCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineCountResp) Reset() {
	*x = GetOnlineCountResp{}
	mi := &file_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineCountResp) ProtoMessage() {}

func (x *GetOnlineCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineCountResp.ProtoReflect.Descriptor instead.
func (*GetOnlineCountResp) Descriptor() ([]byte, []int) {
	return file_websocket_proto_rawDescGZIP(), []int{5}
}

func (x *GetOnlineCountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_websocket_proto protoreflect.FileDescriptor

const file_websocket_proto_rawDesc = "" +
	"\n" +
	"\x0fwebsocket.proto\"c\n" +
	"\x10WebSocketSendReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x19\n" +
	"\bto_users\x18\x02 \x03(\tR\atoUsers\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11WebSocketSendResp\"I\n" +
	"\x10IsOnlineUsersReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\")\n" +
	"\x11IsOnlineUsersResp\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"/\n" +
	"\x11GetOnlineCountReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\"*\n" +
	"\x12GetOnlineCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xb6\x01\n" +
	"\twebsocket\x126\n" +
	"\rwebSocketSend\x12\x11.WebSocketSendReq\x1a\x12.WebSocketSendResp\x126\n" +
	"\risOnlineUsers\x12\x11.IsOnlineUsersReq\x1a\x12.IsOnlineUsersResp\x129\n" +
	"\x0egetOnlineCount\x12\x12.GetOnlineCountReq\x1a\x13.GetOnlineCountRespB\x06Z\x04./pbb\x06proto3"

var (
	file_websocket_proto_rawDescOnce sync.Once
	file_websocket_proto_rawDescData []byte
)

func file_websocket_proto_rawDescGZIP() []byte {
	file_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_proto_rawDesc), len(file_websocket_proto_rawDesc)))
	})
	return file_websocket_proto_rawDescData
}

var file_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_websocket_proto_goTypes = []any{
	(*WebSocketSendReq)(nil),   // 0: WebSocketSendReq
	(*WebSocketSendResp)(nil),  // 1: WebSocketSendResp
	(*IsOnlineUsersReq)(nil),   // 2: IsOnlineUsersReq
	(*IsOnlineUsersResp)(nil),  // 3: IsOnlineUsersResp
	(*GetOnlineCountReq)(nil),  // 4: GetOnlineCountReq
	(*GetOnlineCountResp)(nil), // 5: GetOnlineCountResp
}
var file_websocket_proto_depIdxs = []int32{
	0, // 0: websocket.webSocketSend:input_type -> WebSocketSendReq
	2, // 1: websocket.isOnlineUsers:input_type -> IsOnlineUsersReq
	4, // 2: websocket.getOnlineCount:input_type -> GetOnlineCountReq
	1, // 3: websocket.webSocketSend:output_type -> WebSocketSendResp
	3, // 4: websocket.isOnlineUsers:output_type -> IsOnlineUsersResp
	5, // 5: websocket.getOnlineCount:output_type -> GetOnlineCountResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_websocket_proto_init() }
func file_websocket_proto_init() {
	if File_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_proto_rawDesc), len(file_websocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_proto_depIdxs,
		MessageInfos:      file_websocket_proto_msgTypes,
	}.Build()
	File_websocket_proto = out.File
	file_websocket_proto_goTypes = nil
	file_websocket_proto_depIdxs = nil
}
